#!/usr/bin/env python3
"""QC: numerical traceability + anti-fabrication checks.

- every {{value}} placeholder used in manuscript/main.md must exist in
  manuscript/values.json (which is generated by manuscript_values.py)
- every figure/table file must be cited in the manuscript text
- every reference key in manuscript/references.bib must be cited
- writes qc/numerical_traceability.csv and qc/qc_report.md
"""
import json
import re
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
MS = ROOT / "manuscript"
QC = ROOT / "qc"
QC.mkdir(exist_ok=True)


def main():
    issues = []
    ms = (MS / "main.md").read_text()
    values = json.loads((MS / "values.json").read_text())

    # placeholders
    used = sorted(set(re.findall(r"\{\{([^}]+)\}\}", ms)))
    missing = [k for k in used if k not in values]
    for k in missing:
        issues.append(f"missing value key: {k}")

    # figures cited
    for f in sorted((ROOT / "figures").glob("fig*.png")):
        stem = f.stem
        tag = "Figure " + re.sub(r"\D", "", stem)
        if tag.lower() not in ms.lower():
            issues.append(f"figure not cited: {f.name} (expected '{tag}')")

    # tables cited
    for i in range(1, 5):
        if f"Table {i}" not in ms:
            issues.append(f"Table {i} not cited")

    # references cited
    bib = (MS / "references.bib").read_text() if (MS / "references.bib").exists() else ""
    keys = re.findall(r"@\w+\{([^,]+),", bib)
    built = MS / "build" / "manuscript_final.md"
    if built.exists():
        bt = built.read_text()
        if not re.search(r"\[\d+\]", bt):
            issues.append("no numeric citations found")
        for k in keys:
            if f"[{k}" not in ms and f", {k}" not in ms and f",{k}" not in ms:
                issues.append(f"reference never cited: {k}")
        if re.search(r"\{\{[^}]+\}\}", bt):
            issues.append("unsubstituted placeholders in built manuscript")
    else:
        issues.append("built manuscript missing")
    # citation coverage handled by ordered list check in build script

    # traceability table
    rows = []
    for k in used:
        rows.append({
            "manuscript_location": "manuscript/main.md",
            "placeholder": k,
            "reported_value": values.get(k),
            "source_file": "results/summary_*.csv",
            "generating_script": "scripts/manuscript_values.py",
            "verification_status": "ok" if k in values else "MISSING",
        })
    pd.DataFrame(rows).to_csv(QC / "numerical_traceability.csv", index=False)

    status = "PASS" if not issues else "FAIL"
    report = ["# QC report", "", f"status: {status}", "",
              "## issues"] + [f"- {i}" for i in issues]
    (QC / "qc_report.md").write_text("\n".join(report))
    print(status, len(issues), "issues")


if __name__ == "__main__":
    sys.exit(0 if main() is None else 1)
